LRC-NET-Framework/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LRC_NET_Framework.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using PagedList.Mvc;

namespace LRC_NET_Framework.Controllers
{
    public class AssessmentController : Controller
    {
        private LRCEntities db = new LRCEntities();

        // GET: Assessment
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            var Assessments = db.tb_Assessment.Include(t => t.tb_AssessmentName).Include(t => t.tb_MemberMaster).Include(t => t.tb_AssessmentValue);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Date" : "";
            //Searching @ Filtering
            if (!String.IsNullOrEmpty(searchString))
            {
                Assessments = Assessments.Where(s => s.tb_MemberMaster.LastName.ToUpper().Contains(searchString.ToUpper())
                                       || s.tb_MemberMaster.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }
            //Sorting
            switch (sortOrder)
            {
                case "Name desc":
                    //Activities = Activities.OrderByDescending(s => s.ActivityName);
                    break;
                case "Date":
                    Assessments = Assessments.OrderBy(s => s.AssessmentDate);
                    break;
                //case "Date desc":
                //    tb_MemberMasters = tb_MemberMasters.OrderByDescending(s => s.HireDate);
                //    break;
                default:
                    Assessments = Assessments.OrderByDescending(s => s.AssessmentDate);
                    break;
            }

            //Paging
            int pageSize = 15;
            int pageNumber = (page ?? 1);

            ViewData["MemberQty"] = Assessments.Count();

            return View(Assessments.ToPagedList(pageNumber, pageSize));
            //return View(Assessments.ToList());
        }

        //// GET: Assessment/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tb_Assessment tb_Assessment = db.tb_Assessment.Find(id);
        //    if (tb_Assessment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tb_Assessment);
        //}

        // GET: Assessment/AddPersonAssessmentActivity
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddPersonAssessmentActivity(int? id, int CollegeID)
        {
            //ViewBag.CollegeID = CollegeID;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tb_Assessment = db.tb_Assessment.Include(t => t.tb_MemberMaster);
            tb_Assessment = tb_Assessment.Where(f => f.tb_MemberMaster.MemberID == id);
            tb_Assessment Assessment = new tb_Assessment();
            var userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

            if (tb_Assessment.Count() == 0) //1st Assessment
            {
                Assessment.AddedBy = userId;
                Assessment.AddedDateTime = DateTime.Now;
                Assessment.AssessedBy = userId;
                Assessment.AssessmentDate = DateTime.Now;
                Assessment.AssessmentDesc = String.Empty;
                Assessment.AssessmentNameID = 7; // Add Fee Payer Assess
                Assessment.MemberID = id ?? default(int);
                Assessment.ModifiedBy = userId;
                Assessment.ModifiedDateTime = DateTime.Now;
                Assessment.ValueID = 1;
            }
            else
                Assessment = tb_Assessment.FirstOrDefault();

            SelectList FeePayerAssess = new SelectList(db.tb_AssessmentName.OrderBy(s => s.AssessmentName), "AssessmentNameID", "AssessmentName", Assessment.AssessmentNameID /* selected value */);
            ViewBag.AssessmentNameID = FeePayerAssess;

            SelectList AssessmentValue = new SelectList(db.tb_AssessmentValue, "ValueID", "ValueName", Assessment.ValueID /* selected value */);
            ViewBag.ValueID = AssessmentValue;

            SelectList AspNetUsers = new SelectList(db.AspNetUsers.OrderBy(s => s.LastFirstName), "Id", "LastFirstName");
            ViewBag.AssessedBy = AspNetUsers;

            List<tb_ActivityStatus> ActivityStatuses = new List<tb_ActivityStatus>();

            ViewBag.ActivityStatus = db.tb_ActivityStatus.ToList();
            ViewBag.ActivityStatusAfter = new List<SelectListItem>
                {
                    new SelectListItem { Value = "0", Text = "Participated", Selected = false},
                    new SelectListItem { Value = "1", Text = "Not Participated", Selected = false}
                };

            SelectList Activities = new SelectList(db.tb_Activity.OrderBy(s => s.ActivityName), "ActivityID", "ActivityName");
            SelectListItem selListItem = new SelectListItem() { Value = "0", Text = " Select Activity " };
            ViewBag.ActivityID = CommonFunctions.AddFirstItem(Activities, selListItem);

            List<tb_MemberActivity> MemberActivities = new List<tb_MemberActivity>();
            MemberActivities = db.tb_MemberActivity.Where(a => a.MemberID == id).OrderBy(s => s.ActivityID).ToList();

            tb_MemberMaster fm = db.tb_MemberMaster.Find(id);
            ViewBag.MemberName = fm.LastName + ", " + fm.FirstName;

            var model = new AssessActivityModels()
            {
                _Assessment = Assessment,
                _Activity = db.tb_Activity.FirstOrDefault(),
                _ActivityStatus = ActivityStatuses,
                _MemberActivity = MemberActivities,
                _MemberAssessments = tb_Assessment.ToList(),
                _CollegeID = CollegeID
            };

            return View(model);
        }

        // POST: Assessment/AddPersonAssessmentActivity
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddPersonAssessmentActivity(int id, string submit, int AssessmentNameID, string AssessedBy, int ActivityID, 
            int ActivityStatusID, int ValueID, AssessActivityModels model, FormCollection formCollection)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Error error = new Error();
            error.errCode = ErrorDetail.Success;
            List<string> errs = new List<string>();
            string userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();
            //string uLastFirstName = db.AspNetUsers.Where(s => s.Email == uName).FirstOrDefault().LastFirstName;

            //ViewBag.CollegeID = CollegeID;

            #region Prepare Model (ASSESSMENT Part)

            SelectList FeePayerAssess = new SelectList(db.tb_AssessmentName.OrderBy(s => s.AssessmentName), "AssessmentNameID", "AssessmentName", AssessmentNameID /* selected value */);
            ViewBag.AssessmentNameID = FeePayerAssess;

            SelectList AssessmentValue = new SelectList(db.tb_AssessmentValue, "ValueID", "ValueName", ValueID /* selected value */);
            ViewBag.ValueID = AssessmentValue;

            SelectList AspNetUsers = new SelectList(db.AspNetUsers.OrderBy(s => s.LastFirstName), "Id", "LastFirstName");
            ViewBag.AssessedBy = AspNetUsers;

            model._Assessment.ValueID = ValueID;
            model._Assessment.AssessmentNameID = AssessmentNameID;
            model._Assessment.AssessedBy = AssessedBy;
            model._Assessment.AddedDateTime = DateTime.Now;
            model._MemberAssessments = db.tb_Assessment.Where(f => f.tb_MemberMaster.MemberID == id).ToList();

            #endregion

            #region Prepare Model (ACTIVITY Part)

            model._ActivityStatus = db.tb_ActivityStatus.ToList();

            ViewBag.ActivityStatusAfter = new List<SelectListItem>
            {
                new SelectListItem { Value = "0", Text = "Participated", Selected = false},
                new SelectListItem { Value = "1", Text = "Not Participated", Selected = false}
            };

            SelectList Activities = new SelectList(db.tb_Activity.OrderBy(s => s.ActivityName), "ActivityID", "ActivityName");
            SelectListItem selListItem = new SelectListItem() { Value = "0", Text = " Select Activity " };
            ViewBag.ActivityID = CommonFunctions.AddFirstItem(Activities, selListItem);

            model._MemberActivity = db.tb_MemberActivity.Where(s => s.MemberID == id).ToList();

            tb_MemberMaster fm = db.tb_MemberMaster.Find(id);
            ViewBag.MemberName = fm.LastName + ", " + fm.FirstName;

            #endregion

            if (submit == "Submit") //Adding Assessment
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        model._Assessment.AddedBy = userId;
                        db.tb_Assessment.Add(model._Assessment);
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException ex)
                    {
                        error.errCode = ErrorDetail.DataImportError;
                        error.errMsg = ErrorDetail.GetMsg(error.errCode);

LRC-NET-Framework/Views/Assessment/AddAssessment.cshtml
@model LRC_NET_Framework.tb_Assessment

@{
    ViewBag.Title = "AddAssessment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Add Assessement</h4></div>

@using LRC_NET_Framework.Helpers
@Html.CreateList(ViewData["ErrorList"] as List<string>)

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-horizontal">

    @using (Html.BeginForm("AddAssessment", "Assessment", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MemberID)
        <div class="form-group">

            <div class="col-md-5">

                <div class="col-md-5 col-md-offset-1" id="AssessmentDate">
                    <span class="text-danger">*</span>@Html.Label("AssessmentDate", "Assessment Date", htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.AssessmentDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                    @Html.ValidationMessageFor(model => model.AssessmentDate, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-6" id="AssessedBy">
                    <span class="text-danger">*</span>@Html.Label("AssessedBy", "Assessment By", htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("AssessedBy", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssessedBy, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-6 col-md-offset-1" id="AssessmentNameID">
                    <span class="text-danger">*</span>@Html.Label("AssessmentNameID", "Assessment", htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("AssessmentNameID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssessmentNameID, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-4" id="ValueID">
                    <span class="text-danger">*</span>@Html.Label("ValueID", "Assessment Value", htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("ValueID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ValueID, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="col-md-7">

                <div class="col-md-12" id="Evaluation">
                    <span class="text-danger">*</span>@Html.Label("Evaluation", "Evaluation", htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.Evaluation, new { @class = "form-control", @required = "required", @cols = "100", @rows = "4", @style = "width:100%;" })
                    @Html.ValidationMessageFor(model => model.Evaluation, "", new { @class = "text-danger" })
                </div>

            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-4">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

        @if (ViewBag.MemberAssessments.Count > 0)
        {
        <div class="col-md-12" id="Assessment" style="font-size:smaller; background-color:lavender; border:solid; margin-top:40px; margin-bottom:10px; border-radius:5px; border-width:1px; border-color:gainsboro">

            <div style="background-color:gainsboro; padding-bottom:5px; padding-left:30px; border-bottom-left-radius:5px; border-bottom-right-radius:5px;">@Html.Label("Assessment", "Member Assessments", htmlAttributes: new { @class = "control-label", style = "font-size:larger;" })</div>

            <table class="table">
                <tr class="text-info">
                    <th style="width:20%">
                        Assessment
                    </th>
                    <th>
                        Assessment Date
                    </th>
                    <th>
                        Assessment Value
                    </th>
                    <th>
                        Evaluation
                    </th>
                    <th>
                        Assessed By
                    </th>
                    @*<th>
                    </th>*@
                </tr>
                @foreach (var myVal in ViewBag.MemberAssessments as List<tb_Assessment>)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => myVal.tb_AssessmentName.AssessmentName)
                        </td>
                        <td>
                            @Convert.ToDateTime(myVal.AssessmentDate).ToString("MM/dd/yyyy")
                        </td>
                        <td>
                            @Html.DisplayFor(m => myVal.tb_AssessmentValue.ValueName)
                        </td>
                        <td>
                            @Html.DisplayFor(m => myVal.Evaluation)
                        </td>
                        <td>
                            @Html.DisplayFor(m => myVal.AspNetUsers1.LastFirstName)
                        </td>
                        @*<td>
                            <a href="@Url.Action("DeleteAssessment", "Assessment", new { @AssessmentID = myVal.AssessmentID, MemberId = myVal.MemberID, CollegeID = ViewBag.CollegeID })" class="btn btn-xs"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                        </td>*@
                    </tr>
                }
            </table>
        </div>
        }
<div class="col-md-12">
    @Html.ActionLink("Assessments List", "Index")
</div>
<hr />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Assessment/Delete.cshtml
@model LRC_NET_Framework.tb_Assessment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_Assessment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssessmentDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessmentDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssessmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessmentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssessedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_AssessmentName.AssessmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_AssessmentName.AssessmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_MemberMaster.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_MemberMaster.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LRC-NET-Framework/Views/Assessment/Details.cshtml
@model LRC_NET_Framework.tb_Assessment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tb_Assessment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssessmentDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessmentDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssessmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessmentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssessedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_AssessmentName.AssessmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_AssessmentName.AssessmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_MemberMaster.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_MemberMaster.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AssessmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LRC-NET-Framework/Views/Assessment/Index.cshtml
@*@model IEnumerable<LRC_NET_Framework.tb_Assessment>*@
@model PagedList.IPagedList<LRC_NET_Framework.tb_Assessment>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<ul class="list-inline">
    <li role="button"><a href="@Url.Action("NotSure", "Assessment")" class="btn btn-info viewDialog", data-dialog-title="Question">&nbsp;Assessment<span class="glyphicon glyphicon-plus pull-left" aria-hidden="true"></span></a></li>
    @*<li role="button"><a href="#" class="btn btn-info">&nbsp;Reports<span class="glyphicon glyphicon-stats pull-left" aria-hidden="true"></span></a></li>*@
</ul>

<h2>All Assessments</h2>
@using (Html.BeginForm("Index", "Assessment", FormMethod.Post, new { @class = "margin-right: 0" }))
{
    <div class="form-group row list-inline">
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
                @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Search" })
            </div>
        </div>
    </div>
}
<div class="row ex1">
    <div class="col-md-2 align-text-top"><small>Showing @Model.FirstItemOnPage - @Model.Count()&nbsp;&nbsp;of&nbsp;&nbsp;@ViewData["MemberQty"]</small></div>
    <div class="col-md-3 align-text-top"></div>
    <div class="col-md-7"></div>
</div>

<table class="table">
    <tr>
        <th>
            Faculty Member
        </th>
        <th>
            Assessment
        </th>
        <th>
            Value
        </th>
        <th>
            @Html.ActionLink("Assessment Date", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            Assessed By
        </th>
        <th>
            Added By
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.tb_MemberMaster.LastName + ", " + item.tb_MemberMaster.FirstName, "Details", "Home", new { id = item.tb_MemberMaster.MemberID }, new { @class = "text -info" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tb_AssessmentName.AssessmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tb_AssessmentValue.ValueName)
            </td>
            <td>
                @Convert.ToDateTime(item.AssessmentDate).ToString("MM/dd/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUsers1.LastFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUsers.LastFirstName)
            </td>
        </tr>
    }

</table>
<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) from @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

    @section Scripts {
        <script src='@Url.Content("~/Scripts/jquery-1.12.4.min.js")' type="text/javascript"></script>
        <script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")' type="text/javascript"></script>
        <link href="~/Content/themes/base/all.css" rel="stylesheet" />
        <script>
            $(document).ready(function () {

                $.ajaxSetup({ cache: false });

                $(".viewDialog").on("click", function (e) {
                    e.preventDefault();

                    $("<div></div>")
                        .addClass("dialog")
                        .appendTo("body")
                        .dialog({
                            closeText: "",
                            title: $(this).attr("data-dialog-title"),
                            close: function () { $(this).remove() },
                            height: 300,
                            width: 500,
                            modal: true
                        })
                        .load(this.href);
                });
            });
        </script>

        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

LRC-NET-Framework/Views/Assessment/NotSure.cshtml
@{
    Layout = null;
}
<div>
    <hr />
    <h2>To Be Done</h2>
    <div class="col-md-11 col-md-offset-1">
        <span class="text-danger">
            Not sure which action should be here.
            Just add new Assessment not associated with specific member?
        </span>
    </div>
    <hr>
    <hr>
    <div class="col-md-11 col-md-offset-1">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>