LRC-NET-Framework/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LRC_NET_Framework;
using LRC_NET_Framework.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using PagedList.Mvc;

namespace LRC_NET_Framework.Controllers
{
    public class ActivitiesController : Controller
    {
        private LRCEntities db = new LRCEntities();

        // GET: Activities
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            var Activities = db.tb_Activity.Include(t => t.tb_MemberActivity);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            //Searching @ Filtering
            if (!String.IsNullOrEmpty(searchString))
            {
                Activities = Activities.Where(s => s.ActivityName.ToUpper().Contains(searchString.ToUpper()));
            }
            //Sorting
            switch (sortOrder)
            {
                case "Name desc":
                    Activities = Activities.OrderByDescending(s => s.ActivityName);
                    break;
                //case "Date":
                //    tb_MemberMasters = tb_MemberMasters.OrderBy(s => s.HireDate);
                //    break;
                //case "Date desc":
                //    tb_MemberMasters = tb_MemberMasters.OrderByDescending(s => s.HireDate);
                //    break;
                default:
                    Activities = Activities.OrderBy(s => s.ActivityName);
                    break;
            }

            //Paging
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            ViewData["MemberQty"] = Activities.Count();


            return View(Activities.ToPagedList(pageNumber, pageSize));
        }

        // GET: Activities/Create
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateActivity(string callback, int? memberId, int? returnCollegeID)
        {
            ActivityModels activityModel = new ActivityModels {
                _Callback = callback,
                _MemberId = memberId ?? 0,
                _ReturnCollegeID = returnCollegeID ?? 0,
                _Campuses = new SelectList(db.tb_Campus.OrderBy(s => s.CampusName), "CampusID", "CampusName"),
                _ActivityDate = DateTime.UtcNow
            };
            activityModel._Colleges = new List<SelectListItem>
            { new SelectListItem() {Value = "0", Text = "-- Select One --" }}.Concat(db.tb_College.Select(x => new SelectListItem
                { Value = x.CollegeID.ToString(), Text = x.CollegeName }));

            return View(activityModel);
        }

        // POST: Activities/Create
        [HttpPost]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateActivity([Bind(Include = "_ActivityName,_ActivityDate,_ActivityNote,_CollegeID,_CampusID,_Callback,_MemberId,_ReturnCollegeID")] ActivityModels model, FormCollection formCollection)
        {
            Error error = new Error();
            error.errCode = ErrorDetail.Success;
            error.errMsg = ErrorDetail.GetMsg(error.errCode);
            List<string> errs = new List<string>();

            model._Colleges = new List<SelectListItem>
            { new SelectListItem() {Value = "0", Text = "-- Select One --" }}.Concat(db.tb_College.Select(x => new SelectListItem
            { Value = x.CollegeID.ToString(), Text = x.CollegeName }));
            model._Campuses = new SelectList(db.tb_Campus.Where(s => s.CollegeID == model._CollegeID).OrderBy(s => s.CampusName), "CampusID", "CampusName");

            var userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();
            using (LRCEntities context = new LRCEntities())
            {
                tb_Activity tb_Activity = new tb_Activity
                {
                    ActivityName = model._ActivityName,
                    ActivityDate = model._ActivityDate,
                    CampusID = model._CampusID,
                    ActivityNote = model._ActivityNote,
                    AddedBy = userId,
                    AddedDateTime = DateTime.UtcNow
                };
                context.tb_Activity.Add(tb_Activity);
                try
                {
                    context.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    error.errCode = ErrorDetail.DataImportError;
                    error.errMsg = ErrorDetail.GetMsg(error.errCode);
                    foreach (DbEntityValidationResult validationError in ex.EntityValidationErrors)
                    {
                        error.errMsg += ". Object: " + validationError.Entry.Entity.ToString();
                        foreach (DbValidationError err in validationError.ValidationErrors)
                        {
                            error.errMsg += ". " + err.ErrorMessage;
                        }
                    }
                    errs.Add("Error #" + error.errCode.ToString() + "!" + error.errMsg);
                    ViewData["ErrorList"] = errs;
                    return View(model);
                }
            }
            switch (model._Callback)
            {
                case "AddActivityByMember":
                    return RedirectToAction("AddActivityByMember");
                case "AddActivity":
                    return RedirectToAction("AddActivity", new { @id = model._MemberId });
                case "AddPersonAssessmentActivity":
                    return RedirectToAction("AddPersonAssessmentActivity", "Assessment", new { @id = model._MemberId, CollegeID = model._ReturnCollegeID });
                default:
                    break;
            }
            return View(model);
        }

        public JsonResult GetCampussesByCollegeId(int CollegeId)
        {
            List<tb_Activity> activities = new List<tb_Activity>();
            string json = String.Empty;
            using (LRCEntities context = new LRCEntities())
            {
                SelectList Campuses = new SelectList(context.tb_Campus.Where(s => s.CollegeID == CollegeId).OrderBy(s => s.CampusName), "CampusID", "CampusName");
                json = JsonConvert.SerializeObject(Campuses, Formatting.Indented);
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }


        // GET: Activities/Create
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddActivity(int id)
        {
            List<string> errs = new List<string>();

            ActivityByMemberModels memberActivities = new ActivityByMemberModels();
            using (LRCEntities context = new LRCEntities())
            {
                var tb_MemberMaster = context.tb_MemberMaster.ToList();
                ViewBag.ActivityStatus = context.tb_ActivityStatus.ToList();
                ViewBag.ActivityStatusAfter = new List<SelectListItem>
                {
                    new SelectListItem { Value = "0", Text = "Participated", Selected = false},
                    new SelectListItem { Value = "1", Text = "Not Participated", Selected = false}
                };

                SelectList Activities = new SelectList(db.tb_Activity.OrderBy(s => s.ActivityName), "ActivityID", "ActivityName");
                SelectListItem selListItem = new SelectListItem() { Value = "0", Text = " Select Activity " };
                ViewBag.ActivityID = CommonFunctions.AddFirstItem(Activities, selListItem);
            }
            memberActivities.MemberID = id;
            ViewBag.MemberActivities = db.tb_MemberActivity.Where(a => a.MemberID == id).OrderBy(s => s.ActivityID).ToList();
            tb_MemberMaster fm = db.tb_MemberMaster.Find(id);
            ViewBag.MemberName = fm.LastName + ", " + fm.FirstName;
            return View(memberActivities);
        }

        // POST: Activities/AddActivity
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddActivity([Bind(Include = "MemberID,ActivityID,ActivityStatusID")] ActivityByMemberModels model, FormCollection formCollection)
        {
            Error error = new Error();
            error.errCode = ErrorDetail.Success;
            List<string> errs = new List<string>();

            #region Prepare Model
            ViewBag.ActivityStatus = db.tb_ActivityStatus.ToList();
            ViewBag.ActivityStatusAfter = new List<SelectListItem>
                {
                    new SelectListItem { Value = "0", Text = "Participated", Selected = false},
                    new SelectListItem { Value = "1", Text = "Not Participated", Selected = false}
                };

            SelectList Activities = new SelectList(db.tb_Activity.OrderBy(s => s.ActivityName), "ActivityID", "ActivityName");
            SelectListItem selListItem = new SelectListItem() { Value = "0", Text = " Select Activity " };
            ViewBag.ActivityID = CommonFunctions.AddFirstItem(Activities, selListItem);
            #endregion

            if (ModelState.IsValid)
            {

                bool? isParticipated = null;
                if (formCollection["afterTheFact"] == "0")
                    isParticipated = true;
                else if (formCollection["afterTheFact"] == "1")
                    isParticipated = false;

                string userId = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

                ActivityByMemberModels activityCRUD = new ActivityByMemberModels();

LRC-NET-Framework/Views/Home/AddBuilding.cshtml
@model LRC_NET_Framework.Models.AddBuildingModel
@{
    ViewBag.Title = "Manage Notes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Building Department Management</h4></div>



@using (Html.BeginForm("AddBuilding", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="form-horizontal">
    <fieldset>
        <div class="form-group">
            <div class="col-md-11 col-md-offset-1" id="College">
                @Html.Label("College", "College", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
                @Html.DropDownListFor(model => model._CollegeID, Model._Colleges, new { @id = "Colleges", @class = "form-control", @required = "required", style = "width: 250px;" })
                @Html.ValidationMessageFor(model => model._CollegeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="HiddenBlock" hidden="hidden">

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="Campus">
                    @Html.Label("Campus", "Campus", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
                    @Html.DropDownListFor(model => model._CampusID, Model._Campuses, new { @id = "Campuses", @class = "form-control", @required = "required", style = "width: 250px;" })
                    @Html.ValidationMessageFor(model => model._CampusID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="BuildingName">
                    @Html.Label("BuildingName", "BuildingName", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
                    @Html.EditorFor(model => model._BuildingName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model._BuildingName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="BuildingPicture" style="padding-bottom:15px;">
                    @Html.Label("BuildingPicture", "Picture of Building", htmlAttributes: new { @class = "control-label" })
                    <input class="btn btn-info" type="file" name="file" id="file" />
                    <span class="text-danger">@ViewBag.Message</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-1 col-md-11">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                </div>
            </div>

        </div>

        @using LRC_NET_Framework.Helpers
        @Html.CreateList(ViewData["ErrorList"] as List<string>)

        <div class="col-md-12" id="BuildingList" style="background-color:lavender; border:solid; margin-top:20px; border-radius:5px; border-width:1px; border-color:gainsboro">
            <div style="background-color:gainsboro; padding-bottom:5px; padding-left:30px; border-bottom-left-radius:5px; border-bottom-right-radius:5px;">@Html.Label("BuildingList", "Buildings List", htmlAttributes: new { @class = "control-label", style = "font-size:larger" })</div>

            <table class="table">
                <tr class="text-info">
                    <th class="text-left" width="20%">
                        Campus
                    </th>
                    <th class="text-left">
                        Building
                    </th>
                </tr>
                @foreach (var school in Model._tb_College)
                {
                <tr>
                    <td class="text-left" colspan="2" style="background-color:lightgray; font-weight:bold; border:solid; margin-top:20px; border-radius:5px; border-width:1px; border-color:gainsboro;">
                        @Html.DisplayFor(modelItem => school.CollegeName)
                    </td>
                </tr>
                foreach (var campus in school.tb_Campus)
                {
                    <tr>
                        <td class="text-left">
                            @Html.DisplayFor(modelItem => campus.CampusName)
                        </td>
                        <td class="text-left" style="color:slategrey;padding:5px; margin:5px; ">
                            @foreach (var building in campus.tb_Building)
                            {
                                if (building.ImagePath != null)
                                {
                                    <span style="white-space:nowrap; background-color:gainsboro; padding: 3px 7px 3px 7px; border:solid; border-width:1px; border-color:lightgray; border-radius:3px; line-height: 2">@Html.ActionLink(building.BuildingName, "GetPdfOrJpeg", new { fileName = building.ImagePath, form = "Building" }, new { target = "_blank" })</span>
                                }
                                else
                                {
                                    <span style="white-space:nowrap; background-color:gainsboro; padding: 3px 7px 3px 7px; border:solid; border-width:1px; border-color:lightgray; border-radius:3px; line-height: 2">@building.BuildingName</span>
                                }
                            }
                        </td>
                    </tr>
                }
                 }
            </table>
        </div>

        <div class="col-md-12 text-danger">
            <b>NOTE: </b>Department & Department Group are shared across school. This means you are responsible for maintaining consistent names of your schools. It also means you can't rename them because another local may be used that name. If you see <b>Fine Arts</b> but you want <b>Fine & Applied Arts</b>, then add it. But check to see if <b>Fine and Applied Arts</b> already exist (unless the ampersand is really important to you).
        </div>

    </fieldset>
</div>
}


@section Scripts {
    <script src='@Url.Content("~/Scripts/jquery-1.12.4.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")' type="text/javascript"></script>
    <script type="text/javascript">

$(document).ready(function () {
    if ($("#Colleges").val() != 0) {
        document.getElementById("HiddenBlock").hidden = false;
    }
    $("#Colleges").change(function() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GetCampussesByCollegeId", "Activities")',
            datatype: JSON,
            data: {
                'CollegeId': $("#Colleges").val()
            },
            success: function(data) {
                $('#Campuses').empty();
                var obj = JSON.parse(data);
                if ($("#Colleges").val() != 0) {
                    document.getElementById("HiddenBlock").hidden = false;
                    $.each(obj, function () {
                        $("#Campuses").append($("<option></option >").val(this['Value']).html(this['Text']));
                    });
                }
                else {
                    document.getElementById("HiddenBlock").hidden = true;
                }
            },
            error: function(data) {}
        });
    });
});
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}
@*@section scripts{
        @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
        <script>
            function CollegeChanged() {
                $("#DDLCollege").submit();
            }
        </script>
    }*@

LRC-NET-Framework/Views/Home/AddCopeForm.cshtml
@model LRC_NET_Framework.Models.AddCopeFormModel

@{
    ViewBag.Title = "Manage Notes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Manage COPE Forms (@ViewBag.MemberName)</h4></div>

@using (Html.BeginForm("AddCopeForm", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model._MemberID)
    <div class="col-md-11 col-md-offset-1"><h4>Add COPE Form</h4></div>
    <hr />
    <div class="form-horizontal">
        <fieldset>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="Signed">
                    @Html.Label("Signed", "Signed", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
                    @Html.TextBoxFor(model => model._Signed, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                    @Html.ValidationMessageFor(model => model._Signed, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="MonthlyContribution">
                    @Html.Label("MonthlyContribution", "Monthly Contribution", htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model._MonthlyContribution, new { @class = "form-control", @cols = "100", @rows = "5", @style = "width:120px;" })
                    @Html.ValidationMessageFor(model => model._MonthlyContribution, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="CollectedBy" style="padding-bottom:15px;">
                    @Html.Label("CollectedBy", "Collected By", htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("_CollectedBy", null, htmlAttributes: new { @class = "form-control" })
                    <small><i style="color:gray;">The person who actually took the note. The system is keeping track of the person entering the note (you)</i></small>
                    @Html.ValidationMessageFor(model => model._CollectedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-11 col-md-offset-1" id="Format">
                    @Html.Label("Format", "Download Format: ", htmlAttributes: new { @class = "control-label" })
                    <p class="btn btn-default">PDF, JPEG&nbsp;&nbsp;<span class="glyphicon glyphicon-import" aria-hidden="true"></span></p>
                </div>
                <div class="col-md-11 col-md-offset-1" id="PDF">
                    @Html.Label("PDF", "Upload Form:", htmlAttributes: new { @class = "control-label" })
                    <input class="btn btn-info" type="file" name="file" id="file" />
                    @Html.ValidationMessageFor(model => model._FormImagePath, "", new { @class = "text-danger" })
                    <span class="text-danger">@ViewBag.Message</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-1 col-md-11">
                    <input type="submit" value="Add Membership Form" class="btn btn-primary" />
                </div>
            </div>

            @using LRC_NET_Framework.Helpers
            @Html.CreateList(ViewData["ErrorList"] as List<string>)

            
        @*<div class="col-md-11 col-md-offset-1" id="CopeForms">
            @Html.Label("CopeForms", "COPE Forms", htmlAttributes: new { @class = "control-label" })*@

                <div class="col-md-12" id="CopeForms" style="font-size:smaller; background-color:lavender; border:solid; margin-top:40px; margin-bottom:10px; border-radius:5px; border-width:1px; border-color:gainsboro">
                <div style="background-color:gainsboro; padding-bottom:5px; padding-left:30px; border-bottom-left-radius:5px; border-bottom-right-radius:5px;">@Html.Label("CopeForms", "COPE Forms", htmlAttributes: new { @class = "control-label", style = "font-size:larger;" })</div>
                <table class="table">
                    <tr class="text-info">
                        <th class="text-left">
                            Signed
                        </th>
                        <th class="text-right">
                            Monthly&nbsp;Contribution
                        </th>
                        <th class="text-center">
                            Processed
                        </th>
                        <th class="text-center">
                            Sent&nbsp;To&nbsp;Employer
                        </th>
                        <th class="text-left">
                            Collected&nbsp;By
                        </th>
                        <th class="text-left">
                            Form&nbsp;Image
                        </th>
                        <th class="text-left">
                            Added&nbsp;By
                        </th>
                    </tr>
                    @foreach (var item in Model._CopeForms as List<tb_CopeForms>)
                    {
                        <tr>
                            <td class="text-left">
                                @*@Html.DisplayFor(modelItem => item.Signed, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })*@
                                @Convert.ToDateTime(item.Signed).ToString("MM/dd/yyyy")
                            </td>
                            <td class="text-right">
                                @Html.DisplayFor(modelItem => item.MonthlyContribution)
                            </td>
                            <td class="text-center">
                                @Html.DisplayFor(modelItem => item.Processed)
                            </td>
                            <td class="text-center">
                                @Html.DisplayFor(modelItem => item.SentToEmployer)
                            </td>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.AspNetUsers1.LastFirstName)
                            </td>
                            <td class="text-left">
                                <p>@Html.ActionLink(item.FormImagePath, "GetPdfOrJpeg", new { fileName = item.FormImagePath, form = "CopeForms" }, new { target = "_blank" })</p>
                            </td>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.AspNetUsers.LastFirstName)
                            </td>
                        </tr>
                    }
                </table>
                </div>

        </fieldset>
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "Details", "Home", new { id = Model._MemberID }, new { @class = "text -info" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Home/AddFilterBySchool.cshtml
@{
    Layout = null;
}

@using (Html.BeginForm("MembersBySchool", "Home", FormMethod.Post, new { @class = "margin-right: 0" }))
{
    <div style="font-size:smaller">
        <div class="row" style="margin: 7px">
            @Html.DropDownList("DepartmentID", ViewBag.Departments as SelectList, "-- Select One --", new { @class = "form-control", style = "width: 300px" })
        </div>

        <div class="row" style="margin: 7px">
            @Html.DropDownList("CollegeID", ViewBag.Colleges as SelectList, "-- Select One --", new { @class = "form-control", style = "width: 300px" })
        </div>

        <div style="text-align:center;">
            <button class="btn btn-primary" type="submit">
                <span>&nbsp;&nbsp;Apply&nbsp;Filter<span class="glyphicon glyphicon-filter pull-left" aria-hidden="true"></span></span>
            </button>
        </div>
    </div>
}
    @section scripts{

    }

LRC-NET-Framework/Views/Home/AddFilterHome.cshtml
@{
    Layout = null;
}

@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "margin-right: 0" }))
{
    <div style="font-size:smaller">
        <div class="col-md-6">
            <div class="row" style="margin: 7px">
                @Html.Label("SearchString", "Search String:", htmlAttributes: new { @class = "control-label" })
                @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Search", @Value = (string)ViewBag.Search, style = "width: 230px" })
            </div>

            <div class="row" style="margin: 7px">
                @Html.Label("CollegeID", "College: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("CollegeID", ViewBag.Colleges as SelectList, "-- Select One --", new { @class = "form-control", style = "width: 200px" })
            </div>

            <div class="row" style="margin: 7px">
                @Html.Label("DepartmentID", "Department: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("DepartmentID", ViewBag.Departments as SelectList, "-- Select One --", new { @class = "form-control", style = "width: 250px" })
            </div>

            <div class="row" style="margin: 7px">
                @Html.Label("SemesterID", "Semester: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("SemesterID", (IEnumerable<SelectListItem>)ViewBag.Semesters, "-- Select One --", new { @class = "form-control", style = "width: 250px" })
            </div>
        </div>

        <div class="col-md-6">
            <div class="row" style="margin: 7px">
                @Html.Label("IsActive", "Is Active: ", htmlAttributes: new { @class = "control-label" })
                @Html.CheckBox("IsActive", (bool)ViewBag.IsActive, new { @class = "form-check-input", style = "box-shadow: 2px 2px 2px 0px darkgrey;" })
            </div>
            
            <div class="row" style="margin: 7px;">
                @Html.Label("StatusID", "Status: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("StatusID", (IEnumerable<SelectListItem>)ViewBag.Statuses, "-- Select One --", new { @class = "form-control", style = "width: 200px" })
            </div>

            <div class="row" style="margin: 7px;">  @*pointer-events: none; opacity: 0.4; <- hide item*@
                @Html.Label("ClassCategoryID", "Class Category: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("ClassCategoryID", (IEnumerable<SelectListItem>)ViewBag.ClassCategories, "-- Select One --", new { @class = "form-control", style = "width: 200px" })
            </div>

            <div class="row" style="margin: 7px;">
                @Html.Label("MembershipID", "Membership: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("MembershipID", (IEnumerable<SelectListItem>)ViewBag.Memberships, "-- Select One --", new { @class = "form-control", style = "width: 230px" })
            </div>

            <div class="row" style="margin: 7px;">
                @Html.Label("MembershipCommitmentID", "Membership Commitment: ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("MembershipCommitmentID", (IEnumerable<SelectListItem>)ViewBag.MembershipCommitments, "-- Select One --", new { @class = "form-control", style = "width: 150px" })
            </div>
        </div>
        <div class="col-md-6" style="text-align:right;">
            <button class="btn btn-primary" type="submit">
                <span>&nbsp;&nbsp;Apply&nbsp;Filter<span class="glyphicon glyphicon-filter pull-left" aria-hidden="true"></span></span>
            </button>
        </div>
</div>
    }
    @section scripts{

    }

LRC-NET-Framework/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Local 2279";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    2126 ‘K’ Street<br />
    Sacramento, CA 95816<br />
    <abbr title="Phone">P:</abbr>
    916-448-2452
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
</address>

LRC-NET-Framework/Views/Home/GetCampuses.cshtml
@model IEnumerable<LRC_NET_Framework.tb_Campus>

<div id="searchresults">

    <div class="form-group">
        <div class="col-md-11 col-md-offset-1" id="Campus">
            @Html.Label("Campus", "Campus", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
            @Html.DropDownList("Campus", ViewBag.Campuses as SelectList, new { @class = "form-control", style = "width: 300px" })
            <small><i style="color:gray;">You must select a campus before adding a building</i></small>
            @*@Html.ValidationMessageFor(model => model.CollegeID, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-11 col-md-offset-1" id="Building">
            @Html.Label("Building", "Building", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
            <input type="text" name="BuildingName" class = "form-control" />
            @*@Html.ValidationMessageFor(model   => model.CollegeID, "", new { @class = "text-danger" })*@
        </div>
    </div>

</div>