LRC-NET-Framework/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LRC_NET_Framework;
using PagedList;
using PagedList.Mvc;
using LRC_NET_Framework.Models;
using System.Data.Entity.Validation;

namespace LRC_NET_Framework.Controllers
{
    public class RolesController : Controller
    {
        private LRCEntities db = new LRCEntities();

        // GET: Roles
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            var Roles = db.tb_Roles.Include(t => t.tb_MemberRoles).Where(t => t.tb_MemberRoles.Count != 0);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            //Searching @ Filtering
            if (!String.IsNullOrEmpty(searchString))
            {
                Roles = Roles.Where(s => s.RoleName.ToUpper().Contains(searchString.ToUpper()));
            }
            //Sorting
            switch (sortOrder)
            {
                case "Name desc":
                    //Activities = Activities.OrderByDescending(s => s.ActivityName);
                    break;
                //case "Date":
                //    tb_MemberMasters = tb_MemberMasters.OrderBy(s => s.HireDate);
                //    break;
                //case "Date desc":
                //    tb_MemberMasters = tb_MemberMasters.OrderByDescending(s => s.HireDate);
                //    break;
                default:
                    Roles = Roles.OrderBy(s => s.RoleName);
                    break;
            }

            //Paging
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            ViewData["MemberQty"] = Roles.Count();


            return View(Roles.ToPagedList(pageNumber, pageSize));
            //return View(db.tb_Roles.ToList());
        }

        // GET: Roles/Details/5
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Roles tb_Roles = db.tb_Roles.Find(id);
            if (tb_Roles == null)
            {
                return HttpNotFound();
            }
            return View(tb_Roles);
        }

        // GET: Roles/CreateMemberRoles
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateMemberRoles()
        {
            var members = db.tb_MemberMaster;
            List<object> memberList = new List<object>();
            foreach (var member in members)
                memberList.Add(new
                {
                    Id = member.MemberID,
                    Name = member.LastName + ", " + member.FirstName
                });

            CreateRoleModel model = new CreateRoleModel()
            {
                _MemberID = 0,
                _Members = new SelectList(memberList, "Id", "Name"),
                _RoleID = 0,
                _Roles = new SelectList(db.tb_Roles, "RoleID", "RoleName"),
                _BodyID = 0,
                _Bodies = new SelectList(db.tb_Body, "BodyID", "BodyName"),
                _StartDate = DateTime.Now,
                _EndDate = DateTime.Now
            };

            return View(model);
        }

        // POST: Roles/CreateMemberRoles
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateMemberRoles(CreateRoleModel model)
        {
            if (ModelState.IsValid)
            {
                tb_MemberRoles role = new tb_MemberRoles();
                role.MemberID = model._MemberID;
                role.RoleID = model._RoleID;
                role.BodyID = model._BodyID;
                role.StartDate = model._StartDate;
                role.EndDate = model._EndDate;

                db.tb_MemberRoles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Roles/CreateRole
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateRole()
        {
            return View();
        }

        // POST: Roles/CreateRole
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateRole([Bind(Include = "RoleID,RoleName")] tb_Roles Roles)
        {
            if (ModelState.IsValid)
            {
                db.tb_Roles.Add(Roles);
                db.SaveChanges();
                return RedirectToAction("CreateMemberRoles");
            }

            return View(Roles);
        }

        // GET: Roles/CreateBody
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateBody()
        {
            return View();
        }

        // POST: Roles/CreateRole
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult CreateBody([Bind(Include = "BodyID,BodyName")] tb_Body body)
        {
            if (ModelState.IsValid)
            {
                db.tb_Body.Add(body);
                db.SaveChanges();
                return RedirectToAction("CreateMemberRoles");
            }

            return View(body);
        }

        // GET: Roles/Edit/5

        // GET: Notes/Create
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddRole(int? id)
        {
            //id = 1; // test REMOVE IT
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateRoleModel model = new CreateRoleModel()
            {
                _MemberID = id ?? 0,
                _RoleID = 1,
                _Roles = new SelectList(db.tb_Roles, "RoleID", "RoleName"),
                _BodyID = 1,
                _Bodies = new SelectList(db.tb_Body, "BodyID", "BodyName"),
                _StartDate = DateTime.Now,
                _EndDate = DateTime.Now,
                _MemberRoles = db.tb_MemberRoles.Where(t => t.MemberID == id).ToList()
            };
            return View(model);
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult AddRole(CreateRoleModel model)
        {
            tb_MemberRoles memberRoles = new tb_MemberRoles()
            {
                MemberID = model._MemberID,
                RoleID = model._RoleID,
                BodyID = model._BodyID,
                StartDate = model._StartDate,
                EndDate = model._EndDate
            };
            db.tb_MemberRoles.Add(memberRoles);
            db.SaveChanges();
            model._Roles = new SelectList(db.tb_Roles, "RoleID", "RoleName");
            model._Bodies = new SelectList(db.tb_Body, "BodyID", "BodyName");
            model._MemberRoles = db.tb_MemberRoles.Where(t => t.MemberID == model._MemberID).ToList();
            return View(model);
        }

        [Authorize(Roles = "admin, organizer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Roles tb_Roles = db.tb_Roles.Find(id);
            if (tb_Roles == null)
            {
                return HttpNotFound();
            }
            return View(tb_Roles);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Edit([Bind(Include = "RoleID,RoleName")] tb_Roles tb_Roles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_Roles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_Roles);
        }

        // GET: Roles/Delete/5
        [Authorize(Roles = "admin, organizer")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Roles tb_Roles = db.tb_Roles.Find(id);
            if (tb_Roles == null)
            {
                return HttpNotFound();
            }
            return View(tb_Roles);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, organizer")]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_Roles tb_Roles = db.tb_Roles.Find(id);
            db.tb_Roles.Remove(tb_Roles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

LRC-NET-Framework/Views/Roles/AddRole.cshtml
@model LRC_NET_Framework.Models.CreateRoleModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Manage Roles</h4></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model._MemberID)
        <div class="col-md-11 col-md-offset-1"><h4>Add Role</h4></div>
        <hr />
        @*Roles DDL*@
        <div class="form-group">
            <div class="col-md-11 col-md-offset-1">
                @Html.Label("Role", "Role", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
            </div>
            <div class="col-md-11 col-md-offset-1" id="Role" style="overflow:hidden;">
                <div style="width: 100%;">
                    <div style="float: left;">
                        @Html.DropDownListFor(model => model._RoleID, Model._Roles, new { @class = "form-control", style = "width: 250px;" })
                        @Html.ValidationMessageFor(model => model._RoleID, "", new { @class = "text-danger" })
                    </div>
                    <div style="float: left; margin-left:10px">
                        <a href="@Url.Action("CreateRole", "Roles")" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                    </div>
                </div>
            </div>
        </div>

        @*Bodies DDL*@
        <div class="form-group">
            <div class="col-md-11 col-md-offset-1">
                @Html.Label("Body", "Body", htmlAttributes: new { @class = "control-label" })<span class="text-danger">&nbsp;&nbsp;*</span>
            </div>
            <div class="col-md-11 col-md-offset-1" id="Body" style="overflow:hidden;">
                <div style="width: 100%;">
                    <div style="float: left;">
                        @Html.DropDownListFor(model => model._BodyID, Model._Bodies, new { @class = "form-control", style = "width: 250px;" })
                        @Html.ValidationMessageFor(model => model._BodyID, "", new { @class = "text-danger" })
                    </div>
                    <div style="float: left; margin-left:10px">
                        <a href="@Url.Action("CreateBody", "Roles")" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                    </div>
                </div>
            </div>
        </div>

        @*Start Date*@
        <div class="form-group">
            <div class="col-md-11 col-md-offset-1" id="StartDate">
                <fieldset>
                    <div class="editor-field">
                        @Html.Label("StartDate", "Start Date", htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(m => m._StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                        @Html.ValidationMessageFor(model => model._StartDate)

                    </div>
                </fieldset>
            </div>
        </div>

        @*End Date*@
        <div class="form-group">
            <div class="col-md-11 col-md-offset-1" id="EndDate">
                <fieldset>
                    <div class="editor-field">
                        @Html.Label("EndDate", "End Date", htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(m => m._EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                        @Html.ValidationMessageFor(model => model._EndDate)

                    </div>
                </fieldset>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-11 col-md-offset-1" id="MembershipForms">
                @Html.Label("MembershipForms", "Membership Forms", htmlAttributes: new { @class = "control-label" })
                <table class="table">
                    <tr class="text-info">
                        <th class="text-left" width="20%">
                            Body
                        </th>
                        <th class="text-left">
                            Role
                        </th>
                        <th class="text-left">
                            Start&nbsp;Date
                        </th>

                        <th class="text-left">
                            End&nbsp;Date
                        </th>
                    </tr>
                    @foreach (var item in Model._MemberRoles as List<tb_MemberRoles>)
                    {
                        <tr>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.tb_Body.BodyName)
                            </td>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.tb_Roles.RoleName)
                            </td>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                            </td>
                            <td class="text-left">
                                @Html.DisplayFor(modelItem => item.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>

    </div>
}

    <div class="col-md-offset-1 col-md-11">
        <a href="@Url.Action("Details", "Home", new { id = Model._MemberID })" class="btn btn-info">&nbsp;&nbsp;Back<span class="glyphicon glyphicon-arrow-left pull-left" aria-hidden="true"></span></a>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Roles/CreateBody.cshtml
@model LRC_NET_Framework.tb_Body

@{
    ViewBag.Title = "Add Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Create Body</h4></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BodyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BodyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BodyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
<div class="col-md-offset-1 col-md-11">
    @Html.ActionLink("Back to List", "CreateMemberRoles")
</div>
<hr /><hr /><hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Roles/CreateMemberRoles.cshtml
@model LRC_NET_Framework.Models.CreateRoleModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Add Faculty Member Role</h4></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @*Faculty Members DDL*@
    <div class="form-group">
        <div class="col-md-3">
            <p class="control-label"><span class="text-danger">*</span>  Faculty Member</p>
        </div>
        <div class="col-md-9">
            @Html.DropDownListFor(model => model._MemberID, Model._Members, new { @class = "form-control", style = "width: 250px;" })
            @Html.ValidationMessageFor(model => model._MemberID, "", new { @class = "text-danger" })
        </div>
    </div>

    @*Roles DDL*@
    <div class="form-group">
        <div class="col-md-3">
            <p class="control-label"><span class="text-danger">*</span>  Role</p>
        </div>
        <div class="col-md-9" style="overflow:hidden;">
            <div style="width: 100%;">
                <div style="float: left;">
                    @Html.DropDownListFor(model => model._RoleID, Model._Roles, new { @class = "form-control", style = "width: 250px;" })
                    @Html.ValidationMessageFor(model => model._RoleID, "", new { @class = "text-danger" })
                </div>
                <div style="float: left; margin-left:10px">
                    <a href="@Url.Action("CreateRole", "Roles")" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                </div>
            </div>
        </div>
    </div>

    @*Bodies DDL*@
    <div class="form-group">
        <div class="col-md-3">
            <p class="control-label"><span class="text-danger">*</span>  Body</p>
        </div>
        <div class="col-md-9" style="overflow:hidden;">
            <div style="width: 100%;">
                <div style="float: left;">
                    @Html.DropDownListFor(model => model._BodyID, Model._Bodies, new { @class = "form-control", style = "width: 250px;" })
                    @Html.ValidationMessageFor(model => model._BodyID, "", new { @class = "text-danger" })
                </div>
                <div style="float: left; margin-left:10px">
                    <a href="@Url.Action("CreateBody", "Roles")" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                </div>
            </div>
        </div>
    </div>

    @*Start Date*@
    <div class="form-group">
        <div class="col-md-3">
            <p class="control-label">Start Date</p>
        </div>
        <div class="col-md-9">
            <fieldset>
                <div class="editor-field">
                    @Html.TextBoxFor(m => m._StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                    @Html.ValidationMessageFor(model => model._StartDate)
                </div>
            </fieldset>
        </div>
    </div>

    @*End Date*@
    <div class="form-group">
        <div class="col-md-3">
            <p class="control-label">End Date</p>
        </div>
        <div class="col-md-9">
            <fieldset>
                <div class="editor-field">
                    @Html.TextBoxFor(m => m._EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control datecontrol", type = "date", style = "width: 150px;" })
                    @Html.ValidationMessageFor(model => model._EndDate)

                </div>
            </fieldset>
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div class="col-md-offset-2 col-md-10">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Roles/CreateRole.cshtml
@model LRC_NET_Framework.tb_Roles

@{
    ViewBag.Title = "Add Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="font-weight-bold" style="background-color: #357ebd; border-bottom-left-radius:7px; border-bottom-right-radius:7px; color:gainsboro; padding-top:5px; padding-bottom:5px; padding-left:30px;"><h4>Create Role</h4></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
<div class="col-md-offset-1 col-md-11">
    @Html.ActionLink("Back to List", "CreateMemberRoles")
</div>
<hr /><hr /><hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LRC-NET-Framework/Views/Roles/Delete.cshtml
@model LRC_NET_Framework.tb_Roles

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_Roles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LRC-NET-Framework/Views/Roles/Index.cshtml
@*@model IEnumerable<LRC_NET_Framework.tb_Roles>*@
@model PagedList.IPagedList<LRC_NET_Framework.tb_Roles>
@using PagedList.Mvc
@{
    ViewBag.Title = "Faculty Member Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<ul class="list-inline">
    <li role="button"><a href="@Url.Action("CreateMemberRoles", "Roles")" class="btn btn-default">&nbsp;&nbsp;Role<span class="glyphicon glyphicon-plus pull-left" aria-hidden="true"></span></a></li>
</ul>
<h2>Faculty Member Roles</h2>
@using (Html.BeginForm("Index", "Activities", FormMethod.Post, new { @class = "margin-right: 0" }))
{
    <div class="form-group row list-inline">
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
                @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Search" })
            </div>
        </div>
    </div>
}
<div class="row ex1">
    <div class="col-md-2 align-text-top"><small>Showing @Model.FirstItemOnPage - @Model.Count()&nbsp;&nbsp;of&nbsp;&nbsp;@ViewData["MemberQty"]</small></div>
    <div class="col-md-3 align-text-top"></div>
    <div class="col-md-7"></div>
</div>
<table class="table">
    <tr>
        <th>Faculty Member</th>
        <th>Body</th>
        <th>COPE</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Membership Commitment</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Expired</th>
        <th>Active Status</th>
    </tr>

    @foreach (var role in Model)
    {
        if (role.tb_MemberRoles.Count > 0)
        {
            <tr style="font-weight:bold">
                <td colspan="10" style="background-color:lightgray">
                    @Html.DisplayFor(modelItem => role.RoleName)
                </td>
            </tr>
            foreach (var item in role.tb_MemberRoles)
            {
            <tr>
                <td>
                    @Html.ActionLink(item.tb_MemberMaster.LastName + ", " + item.tb_MemberMaster.FirstName, "Details", "Home", new { id = item.tb_MemberMaster.MemberID }, new { @class = "text -info" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_Body.BodyName)
                </td>
                <td class="danger">
                    ???
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_MemberMaster.tb_MemberPhoneNumbers.Where(t => t.tb_MemberMaster.MemberID == item.tb_MemberMaster.MemberID).FirstOrDefault().PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_MemberMaster.tb_MemberEmail.Where(t => t.tb_MemberMaster.MemberID == item.tb_MemberMaster.MemberID).FirstOrDefault().EmailAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_MemberMaster.tb_MemberActivity.Where(t => t.tb_MemberMaster.MemberID == item.tb_MemberMaster.MemberID).LastOrDefault().MembershipCommitment)
                </td>
                <td>
                    @if (item.StartDate != null)
                    {
                        @Convert.ToDateTime(item.StartDate).ToString("MM/dd/yyyy")
                    }
                </td>
                <td>
                    @if (item.StartDate != null)
                    {
                        @Convert.ToDateTime(item.EndDate).ToString("MM/dd/yyyy")
                    }
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Expired)
                </td>
                <td class="danger">
                    ???
                </td>
            </tr>
            }
        }
    }
        @*@Html.ActionLink("Edit", "Edit", new { id = item.RoleID }) |
            @Html.ActionLink("Details", "Details", new { id = item.RoleID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.RoleID })*@

    </table>
<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) from @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>